name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
    issue-number:  
      description: 'Issue number'
    token:
      description: 'Token'
      default: ${{ github.token}}
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node20'
  main: 'index.js'
