name: JS Action Workflow

on:
  issues:
    types: [opened, edited]

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Say hello
        uses: ./github-actions/actions/js
        with:
          issue-number: ${{ github.event.issue.number }}
          token: ${{ secrets.GITHUB_TOKEN }}