name: JS Action Workflow

on:
  issues:
    types: [opened, edited]

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        uses: ./github-actions/actions/js
        with:
          who-to-greet: ${{ github.event.issue.user.login }}